<?php
/**
 * Description of create
 *
 *  -----------------------------------------------------
 *  Copyright: INETS COMPANY LIMITED
 *  Website: www.inetstz.com
 *  Email: info@inetstz.com
 *  -----------------------------------------------------
 * @author Ephraim Swilla <ephraim@inetstz.com>
 */
?>
<?php
$id = '';
?>

<div class="modal-header"> 
    <h4 class="modal-title">Add Client Payment</h4>
</div>
<div class="modal-body">

    <form class="form-horizontal add_payment_form" data-validate="parsley"> 
	<section class="panel panel-default"> <header class="panel-heading"> 
	    </header> <div class="panel-body">
		<?php if ($id == '') { ?>
    		<div class="form-group"> <label class="col-sm-3 control-label">Client Name</label> 
    		    <div class="col-sm-9">
    			<select data-required="true" id="client_id" class="form-control m-t parsley-validated select2"> 
    			    <option value="">Choose client Name</option> 
				<?php
				$clients = \App\Http\Controllers\Controller::get_all_clients(); // this method will be changed later if the loading speed is small.  We will enable someone to fetch for the client name and do auto complete
				foreach ($clients as $client) {
				    ?>
				    <option value="<?= $client->client_id ?>"><?= $client->name.' ('.$client->phone_number.')' ?></option> 
				<?php } ?>
    			</select>
    		    </div>

    		</div> <div class="line line-dashed line-lg pull-in"></div>
		<?php } ?>
		<div class="form-group"> <label class="col-sm-3 control-label">Transaction Code</label> 
		    <div class="col-sm-9">
			<input type="text" id="transaction_code" class="form-control parsley-validated" data-required="true" placeholder="required field">
			<span>This will be our receipt number or receipt number generated by that third part (e.g M-pesa transaction code or bank receipt code)</span>
			<select data-required="true" id="method" class="form-control m-t parsley-validated"> ;
			    <option value="">Payment Method</option> 
			    <option value="mpesa">M-pesa</option> 
			    <option value="tigopesa">TigoPesa</option>
			    <option value="airtel">Airtel</option> 
			    <option value="bank">Bank Deposit</option> 
			    <option value="cash">Cash</option> 
			    <option value="other">other</option>
			</select>
		    </div>

		</div> <div class="line line-dashed line-lg pull-in"></div> 

		<div class="line line-dashed line-lg pull-in"></div>
		<div class="form-group"> <label class="col-sm-3 control-label">Cost per SMS</label> 
		    <div class="col-sm-9"> 
			<input type="text" id="cost_per_sms" data-maxlength="6" class="form-control parsley-validated" placeholder=""> </div> </div> 

		<div class="line line-dashed line-lg pull-in"></div>
		<div class="form-group">
		    <label class="col-sm-3 control-label">Amount</label> <div class="col-sm-9"> <div class="row"> 
			    <div class="col-sm-6">
				<input type="text" value="" id="amount" class="form-control"></div>
			    <div class="col-sm-6">
				<select data-required="true" id="currency" class="form-control parsley-validated">
				    <option value="">Currency</option> 
				    <option value="TZS">TZS</option> 
				    <option value="USD">USD</option>
				    <option value="KSH">KSH</option> 
				    <option value="other">other</option>
				</select>
			    </div> </div> </div>
		</div> 
	    </div>
	    <footer class="panel-footer text-right bg-light lter"> 
		<button type="button" class="btn btn-success btn-s-xs" onclick="add_payment()">Submit</button> </footer> 
	    <?php if ($id != '') { ?>
    	    <input type="hidden" id="client_id" value="<?=$_GET['id'] ?>"/>
	    <?php } ?>
	</section>
    </form>
    <div id="status_results"></div>
</div>

<script type="text/javascript">
    add_payment = function () {
	var transaction_code = $('#transaction_code').val();
	var method = $('#method').val();
	var client_id = $('#client_id').val();
	var cost_per_sms = $('#cost_per_sms').val();
	var currency = $('#currency').val();
	var amount = $('#amount').val();
	var sms_provided = amount / cost_per_sms;
	$.get('store_payment',
		{currency: currency, amount: amount, transaction_code: transaction_code, cost_per_sms: cost_per_sms, method: method, client_id: client_id, confirmed: '1', staff_id_approved: '1', approved: '1', payment_per_sms: '1', sms_provided: sms_provided}, function (data) {
	    $('#status_results').html(data).addClass('alert alert-success');
            swal('success',data);
	});
    }
</script>